version: '3.1'

services:
  app:
    container_name: spring-boot-rest
    image: 'spring-boot-rest:latest'
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users