# server
server:
  port: 8081
  servlet:
    context-path:
  error:
    include-message: always

# db
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

