# server
server:
  port: ${app_port:8081}
  servlet:
    context-path: /api/v1/
  error:
    include-message: always
    include-binding-errors: always

# db
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/users
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users
        temp:
          use-jdbc-metadata: false
    show-sql: false
